spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=true

eureka.instance.instance-id=${spring.application.name}:${random.uuid}

#Deshabilita la estrategia predeterminada de balanceo de carga
spring.cloud.loadbalancer.ribon.enabled=false

#Son una lista de puntos de entrada
spring.cloud.gateway.routes[0].id=ms-catalogo
spring.cloud.gateway.routes[0].uri=lb://MS-CATALOGO
spring.cloud.gateway.routes[0].predicates[0]=Path:/api/productos/**, /api/categorias/**, /api/imagenes/**

spring.cloud.gateway.default-filters=TokenRelay

spring.security.oauth2.client.provider.keycloak.issuer.uri=http://localhost:8080/realms/mycompany-microservices-realm
spring.security.oauth2.client.registration.spring-cloud-gateway-client.clientid=spring-cloud-gateway-client
spring.security.oauth2.client.registration.spring-cloud-gateway-client.client-secret=ciiN0kyBayCI9sFS3jBV3TyW06QkgZVj
spring.security.oauth2.client.registration.spring-cloud-gateway-client.provider=keycloak
spring.security.oauth2.client.registration.spring-cloud-gateway-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spring-cloud-gateway-client.redirect-uri=http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client